### ISSUE TITLE
Unable to get newly installed worldmode to work.

### ISSUE THREAD

**Issue by inviktus** [sunkid/WorldModes#5]
I recently installed worldmode, but have been unsuccessful at getting it to start properly.

I am running CB RB #1337, worldmode 2.3 and basebukkiteplugin available from this link:
 https://github.com/sunkid/BaseBukkitPlugin/raw/master/release/BaseBukkitPlugin.jar (unsure of version)

I did run it first without the basebukkitplugin.jar, but worldmode wouldn't start nor did it download anything.

here is a pastie of all the error info relating to the failed worldmode startup.
http://pastie.org/2761420

**Comment by sunkid** [comment]
This sounds like this bug: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=501487 . The recommended fix is to install the ca-certificates-java package.

**Comment by inviktus** [comment]
Thank you for the information. 
I have opted for a different plugin, at least for the time being.

I'm not much of a linux user, and I'm not keen to go messing around in there in case I screw something up..
Is installing that package a simple affair?

Thanks again for the help.

p.s as there are other plugins which perform the same functions as yours, I'm wondering why your plugin is the only one
in the 9 months I've been using mineOS to run my server, that has had any kind of problem with the non-standard JRE?
Just a curiosity, not a criticism. I know little of such matters :)

**Comment by sunkid** [comment]
I can understand that you don't want to mess with a perfectly working install. However, installing a package is very straight forward in linux, although the exact command depends on your specific distribution. All the above mentioned package adds is a file with security certificates needed by java in order to be able to make secure http (https) connections. WorldModes uses those to do a version check for BaseBukkitPlugin and to download it if it is not already there.

I will make that process more fail safe so that the plugin will accept an already installed BaseBukkitPlugin without choking. One thing you might want to try though is to install BaseBukkitPlugin in your plugin folder and then add to the config.yml file for WorldModes the following node:

```
settings.disable-updates: false
```
